logger:
  # logger mode
  #   value: stdout | single | rotate
  mode: stdout

  # logger level
  #   value: trace | debug | info | [ warning | warn ] | error
  level: trace
  single: # single mode
    path: /tmp/ifman.log
    perm: 0644
  rotate: # rotate mode
    dir: /tmp
    age: 1296000 # in sec
    cut_period: 86400 # in sec

interface:
  - name: generic_test

    # only used for user distinguishing
    description: Generic Config Example

    # interface status
    #   value: down | up
    status: up

    # interface type
    #   value: generic | dummy | vrf | tun | vxlan | wireguard
    type: generic

    # interface config
    config:
      # generic
      mtu: 1200
      master: vrf
      tx_queue_len: 4096
      mac: 94:94:26:ff:00:01

#      # dummy
#      mtu: 1200
#      tx_queue_len: 4096
#      mac: 94:94:26:ff:00:01
#      master: ""

#      # tun
#      mtu: 1400
#      tx_queue_len: 4096
#      master: ""
#      multi_queue: true
#      persist: true

#      # vrf
#      table_id: 200 # 0 - 255
#      mac: 94:94:26:ff:00:01

#      # vxlan
#      mtu: 1500 # 1024 - 65535
#      tx_queue_len: 4096 # 64 - 65535
#      mac: 94:94:26:ff:00:01
#      master: "" # name string or ""
#      vni: 100 # 0 - 2^24
#      src: 192.168.2.2
#      dst: 192.168.3.2
#      ttl: 16 # 0 - 255
#      tos: 7 # 0 - 255
#      learning: false
#      src_port_low: 10240 # 0 - 65535
#      src_port_high: 20480 # 0 - 65535
#      dst_port: 4789 # 0 - 65535

#      # wireguard server
#      mtu: 1400
#      tx_queue_len: 4096
#      master: ""
#      listen_port: 9999 # 0 - 65535
#      private: "yOkvmylKT4LN2o601MiVntwFMWB5bSD9GOCotoyo81I="
#      peer_public: "V628GeW8NyDsqPS1EonOxeLDhPzRikJ4wbcvRhXErho="

#      # wireguard client
#      mtu: 1400
#      tx_queue_len: 4096
#      master: ""
#      endpoint: 1.1.1.1:4444 # udp address with port
#      handshake: 3 # in sec, used for wireguard handshake timer
#      private: "yOkvmylKT4LN2o601MiVntwFMWB5bSD9GOCotoyo81I="
#      peer_public: "V628GeW8NyDsqPS1EonOxeLDhPzRikJ4wbcvRhXErho="

    # offload config
    tso: true
    lro: true
    gso: false
    gro: false

    # reserve path filtering mode config
    #   value: off | strict | loose
    rp_filter: off

    # interface address
    #   both of ipv4 and ipv6 are supported
    address:
      - 192.168.1.1/24

route:
  - dst: 6.6.6.6/32 # destination network
    gw: 127.0.0.1 # gateway address
    table_id: 0 # vrf table_id or 0

verify:
  check_period: 60 # in second
