logger:
  mode: single # stdout/single/rotate
  level: trace # trace/debug/info/[warning|warn]/error
  single: # single mode
    path: /tmp/ifman.log
    perm: 0644
  rotate: # rotate mode
    dir: /tmp
    age: 1296000 # in sec
    cut_period: 86400 # in sec

interface:
  - name: tvrf01
    description: VRF
    status: up
    type: vrf
    config:
     table_id: 200
     mac: 94:94:26:ff:00:01
    tso: false
    lro: false
    gso: false
    gro: false
    rp_filter: off
    address:

  - name: tdummy01
    description: Dummy01
    status: up
    type: dummy
    config:
     mtu: 1300
     tx_queue_len: 4096
     mac: 94:94:26:ff:00:02
     master: tvrf01
    tso: false
    lro: false
    gso: false
    gro: false
    rp_filter: off
    address:
      - 10.10.1.1/32

  - name: ttun01
    description: Tun01
    status: up
    type: tun
    config:
     mtu: 1400
     tx_queue_len: 512
     master: tvrf01
     multi_queue: true
     persist: true
    tso: false
    lro: false
    gso: false
    gro: false
    rp_filter: off
    address:
      - 10.10.2.1/30

  - name: virbr0
    description: virbr0
    status: up
    type: generic
    config:
      mtu: 1500
      master: tvrf01
      tx_queue_len: 4096
      mac: 52:54:00:d3:9d:39
    tso: false
    lro: false
    gso: false
    gro: false
    rp_filter: off
    address:

route:
  - dst: 8.8.8.8/32
    gw: 10.10.2.2
    table_id: 200

verify:
  check_period: 10 # in second
