logger:
  mode: stdout
  level: trace
  single:
    path: /tmp/ifman.log
    perm: 0644
  rotate:
    dir: /tmp
    age: 1296000
    cut_period: 86400

interface:
  - name: vxlan
    description: vxlan
    status: up
    type: vxlan
    config:
      mtu: 1400
      tx_queue_len: 4096
      mac: 94:94:26:ff:00:02
      master: ""
      vni: 100
      src:
      dst: 100.101.16.223
      ttl: 4
      tos: 7
      learning: false
      src_port_low: 10240
      src_port_high: 40960
      dst_port: 4789
    tso: false
    lro: false
    gso: false
    gro: false
    rp_filter: off
    address:
      - 10.11.1.1/30

  - name: dummy
    description: dummy
    status: up
    type: dummy
    config:
      mtu: 1200
      tx_queue_len: 4096
      mac: 94:94:26:ff:DD:01
      master: ""
    tso: false
    lro: false
    gso: false
    gro: false
    rp_filter: off
    address:
      - 10.10.1.1/32

route:

verify:
  check_period: 60

