logger:
  mode: single
  level: debug

  single:
    path: /data/ifman.log
    permit: 0644

  rotate:
    dir: /data/ifman/log
    max_age_sec: 1296000
    period_sec: 86400

interface:
  - type: bridge
    name: bridge0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    mac: 94:94:26:a7:c8:ee
    comment: ""
    multicast_snooping_on: true
    vlan_filtering_on: true

  - type: dummy
    name: dummy0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    mac: 94:94:26:a7:c8:11
    comment: ""

  - type: iptun
    name: ipip0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    comment: ""
    ttl: 16
    tos: 7
    local_ip: 1.1.1.1
    remote_ip: 1.1.1.2

  - type: generic
    name: eth0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    comment: ""

  - type: tun
    name: tun0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    comment: ""
    multi_queue_on: true
    persist_on: true
    queues: 8

  - type: vlan
    name: vlan0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    bind_link: "eth0"
    mac: 94:94:26:a7:c8:11
    comment: ""
    vlan_id: 10
    stacking_on: false

  - type: vrf
    name: vrf0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    mac: 94:94:26:a7:c8:11
    comment: ""
    table_id: 200

  - type: vxlan
    name: vxlan0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    mac: 94:94:26:a7:c8:11
    comment: ""
    vni: 1000
    src_ip: 1.1.1.1
    dst_ip: 2.2.2.2
    ttl: 16
    tos: 7
    checksum: true
    learning_on: false
    src_port_low: 10240
    src_port_high: 40960
    port: 4789
    vtep_name: eth0

  - type: wireguard_ptp_server
    name: wgs0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    comment: ""
    listen_port: 10000
    private: your_key
    peer_public: peer_key
    key_chain: key_chain

  - type: wireguard_ptp_client
    name: wgc0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    comment: ""
    endpoint: 1.1.1.1:6666
    heartbeat_interval: 10
    private: your_key
    peer_public: peer_key
    key_chain: key_chain

  - type: wireguard_origin
    name: wg0
    link_up: true
    tx_queue_len: 1024
    mtu: 1500
    master_name: ""
    comment: ""
    listen_port: 8000
    private: your_key
    peers:
      - peer_public: peer_key
        allowed_cidr:
          - 192.168.1.2/32
        endpoint: 1.1.1.1:6666
        heartbeat_interval: 10

addr:
  - name: eth0
    address: 192.168.1.1/24
    ptp_mode: false
    peer_prefix:

  - name: vx0
    address: 10.1.1.2/32
    ptp_mode: true
    peer_prefix: 10.1.1.1/32

rp_filter:
  - name: eth0
    mode: off

  - name: vx0
    mode: strict

  - name: vx1
    mode: loose

learning:
  - name: vx0
    learning_on: true

  - name: vx1
    learning_on: false

common:
  check_period_sec: 60

