log:
  driver: stdout
  level: debug

  single:
    path: /tmp/ifman.log
    permission: 0644
  
  rotate:
    dir: /tmp/log
    period: 86400
    max_age: 1296000
  
interface:
  driver: local

  local:
    - name: lo

  etcd:
    endpoints: ['', '']
  