// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IfmanClient is the client API for Ifman service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IfmanClient interface {
	ReloadConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadResponse, error)
	Recheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RecheckResponse, error)
}

type ifmanClient struct {
	cc grpc.ClientConnInterface
}

func NewIfmanClient(cc grpc.ClientConnInterface) IfmanClient {
	return &ifmanClient{cc}
}

func (c *ifmanClient) ReloadConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadResponse, error) {
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, "/proto.Ifman/ReloadConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ifmanClient) Recheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RecheckResponse, error) {
	out := new(RecheckResponse)
	err := c.cc.Invoke(ctx, "/proto.Ifman/Recheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IfmanServer is the server API for Ifman service.
// All implementations must embed UnimplementedIfmanServer
// for forward compatibility
type IfmanServer interface {
	ReloadConfig(context.Context, *emptypb.Empty) (*ReloadResponse, error)
	Recheck(context.Context, *emptypb.Empty) (*RecheckResponse, error)
	mustEmbedUnimplementedIfmanServer()
}

// UnimplementedIfmanServer must be embedded to have forward compatible implementations.
type UnimplementedIfmanServer struct {
}

func (UnimplementedIfmanServer) ReloadConfig(context.Context, *emptypb.Empty) (*ReloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedIfmanServer) Recheck(context.Context, *emptypb.Empty) (*RecheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recheck not implemented")
}
func (UnimplementedIfmanServer) mustEmbedUnimplementedIfmanServer() {}

// UnsafeIfmanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IfmanServer will
// result in compilation errors.
type UnsafeIfmanServer interface {
	mustEmbedUnimplementedIfmanServer()
}

func RegisterIfmanServer(s grpc.ServiceRegistrar, srv IfmanServer) {
	s.RegisterService(&Ifman_ServiceDesc, srv)
}

func _Ifman_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IfmanServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ifman/ReloadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IfmanServer).ReloadConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ifman_Recheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IfmanServer).Recheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ifman/Recheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IfmanServer).Recheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Ifman_ServiceDesc is the grpc.ServiceDesc for Ifman service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ifman_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Ifman",
	HandlerType: (*IfmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReloadConfig",
			Handler:    _Ifman_ReloadConfig_Handler,
		},
		{
			MethodName: "Recheck",
			Handler:    _Ifman_Recheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ifman.proto",
}
